### ISSUE TITLE
Problem on Mac

### ISSUE THREAD

**Issue by lufutu** [IronWarrior/UnityGrassGeometryShader#1]
Hi there i have problem when open project on my Mac:
Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
![Screen Shot 2019-04-13 at 12 52 32](https://user-images.githubusercontent.com/238651/56075342-21f65400-5deb-11e9-8461-4a5e76ba057c.png)
Is it my laptop problem or shader bug ?
Thank you

**Comment by kerberjg** [comment]
For some reason this shader doesn't seem work with Metal, which is Mac's default graphics API. If you switch to "OpenGLCore" in Player settings, it works!

![image](https://user-images.githubusercontent.com/16939117/56576621-2ed42e00-65c9-11e9-8d91-f0b3edff3a69.png)

**Comment by lufutu** [comment]
Thank you
