### ISSUE TITLE
Update Shader from URP

### ISSUE THREAD

**Issue by ImanCol** [IronWarrior/UnityGrassGeometryShader#6]
Could you update the project to be compatible with URP ?. Thank you.

**Comment by alicewithalex** [comment]
Hello, I modified some placed in code and it works some how :) Leave me your mail and I send you shader code

**Comment by ImanCol** [comment]
colombiologo10@gmail.com

Thanks

**Comment by tahirali90** [comment]
> Hello, I modified some placed in code and it works some how :) Leave me your mail and I send you shader code

Please share the code with me.

**Comment by matheusfa** [comment]
> Hello, I modified some placed in code and it works some how :) Leave me your mail and I send you shader code

Please share the modified code.

matheusferreiraaraujo@gmail.com

**Comment by cosiugavictor** [comment]
please share to me the modified code, thanks so much !

**Comment by Mctuggernuts25** [comment]
If anyone has the URP version of the shader and necessary files, could you please send them to me at - simpross@yahoo.co.uk

Thank you in advance.

**Comment by sohamtomato** [comment]
Please share the modified code.

skhunt007@gmail.com

**Comment by ImanCol** [comment]
@ColinLeung-NiloCat [has a more elaborate version exclusively in URP ](https://github.com/ColinLeung-NiloCat/UnityURP-MobileDrawMeshInstancedIndirectExample)

**Comment by enesozdemir** [comment]
> Hello, I modified some placed in code and it works some how :) Leave me your mail and I send you shader code

would you share with me too? @meozdemir90@gmail.com

Edit: Okay i think i kinda fixed it, i changed "LightMode" = "ForwardBase" with "LightMode" = "UniversalForward" but my terrain is bigger so i'm not sure if this is gonna work for me
